### ISSUE TITLE
Bug in creating a password while registering a new user.

### ISSUE THREAD

**Issue by viswa4403** [anokha-24/anokha_app#6]
As a new user, I was able to register in the application, without any password constraints. 

When I tried to login into the app, the app asks the password length should be of minimum of 8 characters, but in registration I was able to register with just 5 characters. 
Same goes with the Forgot Password feature.

**Comment by Ashrockzzz2003** [comment]
We are sorry for this bug. 
Thank you for reporting it to us.

Would you like to contribute and fix it @viswa4403?

**Comment by viswa4403** [comment]
Hi @Ashrockzzz2003,
Thank you for the quick response! I'd be happy to contribute and work on fixing this issue.

**Comment by Ashrockzzz2003** [comment]
Awesome! Thank you!
Assigned you to this issue. Raise a PR once you're done with the fix.

**Comment by Ashrockzzz2003** [comment]
FYI
Validation rule is
`<min 8 chars. Max 255 chars. Password cannot have "-" and "'">`

**Comment by viswa4403** [comment]
@Ashrockzzz2003 Noted, thanks for the validation rule details!
